### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by SomebodySysop** [kevinamiri/chatgpt-plugin-googlesearch#1]
root@ASUSET2410-Ubuntu:/home/ron/workarea/openai/chatgpt-plugin-googlesearch# npx ts-node index.ts
/usr/local/lib/node_modules/npm/node_modules/nopt/lib/nopt-lib.js:64
  const StringType = typeDefs.String?.type
                                     ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

Any suggestions?

**Comment by kevinamiri** [comment]
- I simplified the app, and test it on Codespaces, the example is working now.
- About the error you need to upgrade your Nodejs to a newer version of Node.js that supports optional chaining.
